# Generated by Django 3.2.3 on 2021-07-21 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of creation or modifying')),
                ('url', models.CharField(max_length=255, verbose_name='URL of page for parsing')),
                ('token', models.SlugField(unique=True, verbose_name='Request TOKEN')),
                ('results', models.TextField(blank=True, null=True, verbose_name='Request results')),
                ('status', models.IntegerField(choices=[(0, 'In progress'), (1, 'Completed')], default=0, verbose_name='Status')),
            ],
            options={
                'ordering': ['modified'],
            },
        ),
    ]
